package com.soloway.BadRecommender.model.enums;

public enum Topic {
  ENERGY,
  SLEEP_STRESS,
  WEIGHT_CONTROL,
  SKIN_HAIR,
  DIGESTION,
  JOINTS_BONES,
  IMMUNITY,
  HEART_VESSELS,
  THYROID,
  CYCLE_PMS,
  MENOPAUSE,
  MALE_HEALTH,
  HEMOGLOBIN,
  HORMONAL_BALANCE,
  PROSTATE_HEALTH,
  IMMUNE_SYSTEM,
  CARDIOVASCULAR_HEALTH,
  MENTAL_HEALTH
}