services:
  - type: web
    name: bad-recommender
    env: java
    repo: https://github.com/Sikorsky28/BadRecommender-.git
    region: oregon
    plan: free
    buildCommand: "./gradlew clean build -x test"
    startCommand: "java -jar build/libs/BadRecommender-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        value: 1xoz1hpg9XIcci4j9YByJiWQ2PYuiMb2cOX_Nu03rblM
      - key: GOOGLE_CREDENTIALS_FILE
        value: google-credentials.json
      - key: MAIL_HOST
        value: smtp.msndr.net
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: marketing@soloways.ru
      - key: MAIL_PASSWORD
        value: e016348c8debb844652c586076fb1c8f
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.tilda.ws,https://*.tilda.site,https://*.tilda.com,https://your-tilda-site.com,https://www.your-tilda-site.com"
      - key: CACHE_TTL
        value: 300000
      - key: CACHE_MAX_SIZE
        value: 1000
      - key: TELEGRAM_BOT_ENABLED
        value: true
      - key: TELEGRAM_BOT_TOKEN
        value: 7368002281:AAGVqM_9WOoEAgU8f4tdP_F5rnBK-Lsq460
      - key: TELEGRAM_BOT_USERNAME
        value: SolowaysRecommendationsBot
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
