services:
  - type: web
    name: bad-recommender
    env: java
    repo: https://github.com/your-username/BadRecommender  # Замените на ваш репозиторий
    region: oregon  # Или выберите другой регион
    plan: free  # Или starter/standard
    buildCommand: "./gradlew clean build -x test"
    startCommand: "java -jar build/libs/BadRecommender-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        value: 1xoz1hpg9XIcci4j9YByJiWQ2PYuiMb2cOX_Nu03rblM
      - key: MAIL_HOST
        value: smtp.msndr.net
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: marketing@soloways.ru
      - key: MAIL_PASSWORD
        value: e016348c8debb844652c586076fb1c8f
      - key: CORS_ALLOWED_ORIGINS
        value: "*"  # В production замените на реальные домены
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
