server:
  port: ${PORT:8080}  # Render.com использует переменную PORT

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  
  # Конфигурация для production
  application:
    name: bad-recommender
  
  # Конфигурация email
  mail:
    host: ${MAIL_HOST:smtp.msndr.net}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:marketing@soloways.ru}
    password: ${MAIL_PASSWORD:e016348c8debb844652c586076fb1c8f}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
          ssl:
            trust: smtp.msndr.net
            enable: true
          connectiontimeout: 30000
          timeout: 30000
        transport:
          protocol: smtps

# Конфигурация Google Sheets (через переменные окружения)
google:
  sheets:
    spreadsheet-id: ${GOOGLE_SHEETS_SPREADSHEET_ID:1xoz1hpg9XIcci4j9YByJiWQ2PYuiMb2cOX_Nu03rblM}
    credentials-file: ${GOOGLE_CREDENTIALS_FILE:google-credentials.json}

# Настройки кэша для production
cache:
  ttl: ${CACHE_TTL:300000}  # 5 минут в миллисекундах
  max-size: ${CACHE_MAX_SIZE:1000}

# CORS настройки для Tilda
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://*.tilda.ws,https://*.tilda.site,https://*.tilda.com,https://your-tilda-site.com,https://www.your-tilda-site.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
